#@host =https://fhir.dk.swisstph-mis.ch/matchbox/fhir/
@host=https://fhir.ruler.dk.swisstph-mis.ch/fhir/
@rootemcare=/home/delcpa/Development/smart-emcare
##################3 REGISTRATIOn E #############################
###
### update the SM  Encounter

PUT {{host}}StructureMap/emcareb.registration.e HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json;fhirVersion=4.0



< /home/delcpa/Development/smart-emcare/input/mapping/emcareb.registration.e.map

### Test SM encounter against QR
POST {{host}}StructureMap/$transform?source=https://fhir.dk.swisstph-mis.ch/matchbox/fhir/StructureMap/emcareb.registration.e
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./QR.E.json

### update the SM DS

PUT {{host}}StructureMap/emcareb.registration.e HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json;fhirVersion=4.0

< {{rootemcare}}/input/mapping/emcareb.registration.e.map

### Test SM against QR  Encounter
POST {{host}}StructureMap/$transform?source={{host}}StructureMap/emcareb.registration.e
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./QR.E.json

##################3 REGISTRATIOn P #############################
### update the SM 

PUT {{host}}StructureMap/emcarea.registration.p HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json;fhirVersion=4.0



< {{rootemcare}}/input/mapping/emcarea.registration.p.map

### get the SM 

GET {{host}}StructureMap/emcarea.registration.p HTTP/1.1

### Test SM against QR
POST {{host}}StructureMap/$transform?source={{host}}StructureMap/emcarea.registration.p
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./QR_P.json

###
#Bundle

POST {{host}} HTTP/1.1
Content-Type: application/json

< ./test/bundle_P.json

### Test SM against QR
POST {{host}}StructureMap/$transform?source={{host}}StructureMap/emcare.b6.measurements
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./QR_M.json

### send bundle
#Bundle

POST {{host}} HTTP/1.1
Content-Type: application/json

< ./test/bundle_E.json
