@host=https://fhir.ruler.dk.swisstph-mis.ch/fhir
#@host=https://fhir.dk.swisstph-mis.ch/matchbox/fhir

@rootemcare=/home/delcpa/Development/smart-emcare
### library post
PUT {{host}}/Library/emcaredt01
content-type: application/json

< {{rootemcare}}/input/resources/library/library-emcaredt01.json

### library eval POST with get data
POST {{host}}/Library/emcaredt01/$evaluate?subject=/Patient/patient0
http://build.fhir.org/ig/HL7/sdc/
PUT {{host}}/Library/emcareb6measurements
content-type: application/json



< /home/delcpa/Development/smart-emcare/input/resources/library/library-emcare.b6.measurements.json


### post lib 

PUT {{host}}/Library/emcareb6measurements
content-type: text/cql




< /home/delcpa/Development/smart-emcare/input/cql/emcareb6measurements.cql





### library eval POST with get data
PUT {{host}}/Patient/patient0
content-type: application/json

< /home/delcpa/Development/DAK-tools/test/patient.json


### evaluate

GET {{host}}/Library/emcareb6measurements/$evaluate?subject=/Patient/patient0&annotations=true&result-types=true


### evaluate

POST {{host}}/Library/EmCareBase/$evaluate?subject=/Patient/patient0&annotations=true&result-types=true

### seding ucum

PUT {{host}}/ValueSet/ucum-common
content-type: application/json

< {{rootemcare}}/manual/vocabulary/valueset/valueset-ucum-common.json

### $Apply

POST {{host}}/PlanDefinition/emcaredt01/$apply?subject=/Patient/patient0
### Data requirements

GET {{host}}/Library/EmCareBase

### Send FHIRhelper
PUT {{host}}/Library/FHIRHelpers
content-type: application/json

< C:\Users\delcpa\Development\smart-emcare\input\resources\library\library-fhirhelpers.json

###

GET {{host}}/Library/?url=http://fhir.org/guides/who/anc-cds/Library/FHIRHelpers
###
PUT {{host}}/Library/emcareb1014symptoms2mp
content-type: application/json

< {{rootemcare}}/input/resources/library/library-emcare.b10-14.symptoms.2m.p.json

###
### library eval POST with get data
POST {{host}}/Library/emcareb6measurements/$evaluate?subject=/Patient/a122b5ac-a9b5-4fad-93a8-b6a983e6821d&encounter=58868e86-3518-44b3-bf08-56d7aa8d9ed0
### library eval POST with get data
GET {{host}}/Library/emcareb7ltidangersigns/$evaluate?subject=/Patient/patient0

### library eval Symptoms
POST {{host}}/Library/emcareb1014symptoms2mp/$evaluate?subject=/Patient/a122b5ac-a9b5-4fad-93a8-b6a983e6821d&encounter=58868e86-3518-44b3-bf08-56d7aa8d9ed0

### library eval Observation
POST {{host}}/Library/emcareobservation/$evaluate?encounter=/Encounter/58868e86-3518-44b3-bf08-56d7aa8d9ed0

### library eval POST with get data
POST {{host}}/Library/EmCareBase/$evaluate?encounter=/Encounter/58868e86-3518-44b3-bf08-56d7aa8d9ed0
### library eval POST with get data
POST {{host}}/Library/emcarecombineddataelements/$evaluate?subject=/Patient/a122b5ac-a9b5-4fad-93a8-b6a983e6821d
### library eval ZScoreBAse

# emcareb1016signs2mp
#emcareb1014symptoms2mp
# EmCareZScore
# emcarecombineddataelements
# EmCareBase  
# emcaredt01
# emcareb23classification
#emcareobservation
@file = emcarebase
@lib = emcarezscore
PUT {{host}}/Library/{{lib}}
content-type: application/json

< {{rootemcare}}/input/resources/library/library-{{file}}.json
####

@patientid = 2f82c2f5-b57e-4b48-a7ef-327459f6ec99
@encounterid = 0ea41310-0a3e-4390-b621-e3ff45128c92
POST {{host}}/Library/{{lib}}/$evaluate?subject=/Patient/{{patientid}}
content-type: application/json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "parameters",
      "resource": {
        "resourceType": "Parameters",
        "parameter": [
          {
            "name": "encounterid",
            "valueString":"{{encounterid}}"
            
          }
        ]
      }
    }
  ]
}
###
DELETE {{host}}/Encounter/e661c787-9726-443c-825e-08770e403881
###32
    {
    "name":"expression",
    "valueString":"EmCarePatient"

    },
### Send emcarepd lib
PUT {{host}}/Library/emcaredt01
content-type: application/json

< /home/delcpa/Development/smart-emcare/input/resources/library/library-emcaredt01.json
###
GET {{host}}/Library/FHIRHelpers

###
GET https://fhir.ruler.dk.swisstph-mis.ch/fhir/Library/SimpleR4Library

###
GET https://fhir.ruler.dk.swisstph-mis.ch/fhir/Library/emcaredt01
###


GET {{host}}/Observation?subject={{patientid}}
####

GET {{host}}/Observation?encounter=Encounter/0ea41310-0a3e-4390-b621-e3ff45128c92
####

GET {{host}}/?_getpages=a923b847-97f6-4f41-9e97-c4dbd3dd81f5&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"

###


GET {{host}}/Patient/{{patientid}}
###
GET {{host}}/Encounter?subject={{patientid}}
###
DELETE {{host}}/Encounter/encounter0

###
POST https://fhir.ruler.dk.swisstph-mis.ch/fhir/$cql
content-type: application/json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "expression",
      "valueString": "(6.6729 * (4.72545133*-0.0235*0.12333-1)^(1/0.0248))"
    }
  ]
}
####
# true or null -> true  (6.6729 * (4.72545133*-0.0235*0.12333-1)^(1/0.0248))
# false or null -> null  (((12 /6.6729 )^-0.0248  - 1)  / ( 0.12329 * -0.0248))
# false and null -> false 
# true and null -> null 

###resourceType
    {
        "name": "subject",
        "valueReference":{"reference":"/Patient/a122b5ac-a9b5-4fad-93a8-b6a983e6821d"}
    },
### EMCareBAse

POST https://fhir.cql-translator.dk.swisstph-mis.ch/cql/translator?annotations=true&result-types=true HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary
Accept: multipart/form-data


--MyBoundary
Content-Disposition:form-data; name="emcareb6measurements"
Content-Type: application/cql

< /home/delcpa/Development/smart-emcare/input/cql/emcareb6measurements.cql


--MyBoundary
Content-Disposition:form-data; name="FHIRHelpers"
Content-Type: application/cql

< /home/delcpa/Development/smart-emcare/input/cql/FHIRHelpers.cql
--MyBoundary--



####31
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "parameters",
      "resource": {          {
            "name": "encounter",
            "resource":{
              "resourceType": "Encounter",
              "id": "58868e86-3518-44b3-bf08-56d7aa8d9ed0",
              "meta": {
                "versionId": "1",
                "lastUpdated": "2022-11-22T07:45:18.316+00:00",
                "source": "#2Z5sMgKpcgJJZ9kk"
              },
              "extension": [
                {
                  "url": "https://fhir.dk.swisstph-mis.ch/matchbox/fhir/StructureDefinition/refered",
                  "valueBoolean": false
                }
              ],
              "type": [
                {
                  "coding": [
                    {
                      "system": "https://fhir.dk.swisstph-mis.ch/matchbox/fhir/CodeSystem/emcare-custom-codes",
                      "code": "EmCare.B2.DE03",
                      "display": "Unplanned"
                    }
                  ],
                  "text": "type of visit"
                }
              ],
              "subject": {
                "reference": "Patient/7d25cd4d-9865-4c9a-afd6-ab547821b515",
                "type": "Patient"
              }
            }
        "resourceType": "Parameters",
        "parameter": [
          {
            "name": "encounter",
            "resource":{
              "resourceType": "Encounter",
              "id": "58868e86-3518-44b3-bf08-56d7aa8d9ed0",
              "meta": {
                "versionId": "1",
                "lastUpdated": "2022-11-22T07:45:18.316+00:00",
                "source": "#2Z5sMgKpcgJJZ9kk"
              },
              "extension": [
                {
                  "url": "https://fhir.dk.swisstph-mis.ch/matchbox/fhir/StructureDefinition/refered",
                  "valueBoolean": false
                }
              ],
              "type": [
                {
                  "coding": [
                    {
                      "system": "https://fhir.dk.swisstph-mis.ch/matchbox/fhir/CodeSystem/emcare-custom-codes",
                      "code": "EmCare.B2.DE03",
                      "display": "Unplanned"
                    }
                  ],
                  "text": "type of visit"
                }
              ],
              "subject": {
                "reference": "Patient/7d25cd4d-9865-4c9a-afd6-ab547821b515",
                "type": "Patient"
              }
            }
          }
        ]
      }
    },
    {
      "name": "expression",
      "valueString": "Last([Observation])"
    }
  ]
}