#@host = https://test.ahdis.ch


###
#@host =https://fhir.dk.swisstph-mis.ch/matchbox/fhir/
#@host = http://185.11.167.36:8080/matchbox/fhir/

@host=https://fhir.ruler.dk.swisstph-mis.ch/fhir

###
#Bundle

POST {{host}} HTTP/1.1
Content-Type: application/json

< /home/delcpa/Development/DAK-tools/bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\cpg-bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\who_bundle.json
###

#Bundle who

POST {{host}} HTTP/1.1
Content-Type: application/json

< /home/delcpa/Development/smart-emcare/input/ext_ig/who_bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\cpg-bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\who_bundle.json
###

#Bundle cpg

POST {{host}} HTTP/1.1
Content-Type: application/json

< /home/delcpa/Development/smart-emcare/input/ext_ig/cpg-bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\cpg-bundle.json
#< C:\Users\delcpa\Development\smart-emcare\input\ext_ig\who_bundle.json
###

POST {{host}}/ HTTP/1.1
Content-Type: application/json

< C:\Users\delcpa\Development\DAK-tools\bundle.json


###
 DELETE http://185.11.167.36:8080/matchbox/fhir/Questionnaire/emcarea.registration.p

####

PUT http://185.11.167.36:8080/matchbox/fhir/Questionnaire/emcarea.registration.p
Content-Type: application/json

< C:\Users\delcpa\Development\smart-emcare\input\resources\questionnaire\questionnaire-emcarea.registration.p.json


### ANthro


POST https://fhir.cql-translator.dk.swisstph-mis.ch/cql/translator HTTP/1.1
Content-Type: application/cql
Accept: application/elm+json

< C:\Users\delcpa\Development\smart-emcare\input\cql\emcaredt01.cql




