@host =https://fhir.dk.swisstph-mis.ch/matchbox/fhir/
#@host=https://fhir.ruler.dk.swisstph-mis.ch/fhir/

### update the SM 

PUT {{host}}StructureMap/emcarea.registration.p HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json;fhirVersion=4.0



< C:\Users\delcpa\Development\smart-emcare\input\resources\structuremap\structuremap-emcarea.registration.p.map

###

### Test SM against QR
POST {{host}}StructureMap/$transform?source=https://fhir.dk.swisstph-mis.ch/matchbox/fhir/StructureMap/emcarea.registration.p
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< C:\Users\delcpa\Downloads\qr.json
#< C:\Users\delcpa\Development\smart-emcare\input\resources\structuremap\test-qr-emcarea.registration.p.json


### send bundle

POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "resourceType": "Bundle",
  "id": "85121485-03ee-4f78-bbfd-0f9c821db4ab",
  "type": "batch",
  "entry": [
    {
      "id": "4503c065-c965-4267-8dc8-cf42f410736f",
      "resource": {
        "resourceType": "Patient",
        "identifier": [
          {
            "system": "https://fhir.dk.swisstph-mis.ch/matchbox/fhir/CodeSystem/emcare-custom-codes",
            "value": "EmCare.A.DE03"
          }
        ],
        "gender": "male",
        "birthDate": "2022-08-18",
        "address": [
          {
            "text": "this is the address"
          }
        ]
      },
      "request": {
        "url": "/Patient/4503c065-c965-4267-8dc8-cf42f410736f",
        "method": "PUT"
      }
    },
    {
      "id": "4503c065-c965-4267-8dc8-cf42f410736f",
      "resource": {
        "resourceType": "Encounter",
        "subject": {
          "type": "Patient",
          "identifier": {
            "value": "4503c065-c965-4267-8dc8-cf42f410736f"
          }
        }
      },
      "request": {
        "url": "/Encounter/4503c065-c965-4267-8dc8-cf42f410736f",
        "method": "PUT"
      }
    },
    {
      "id": "eessssd-324534-34534-3455",
      "resource": {
        "resourceType": "RelatedPerson",
        "telecom": [
          {
            "system": "phone",
            "value": "123",
            "use": "mobile"
          },
          {
            "system": "phone",
            "value": "124",
            "use": "home"
          },
          {
            "system": "phone",
            "value": "123",
            "use": "work"
          }
        ]
      },
      "request": {
        "url": "/RelatedPerson/eessssd-324534-34534-3455",
        "method": "PUT"
      }
    },
    {
      "resource": {
        "resourceType": "CommunicationRequest",
        "category": [
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/ValueSet/communication-category",
                "code": "notification"
              }
            ]
          }
        ],
        "subject": {
          "type": "Patient",
          "identifier": {
            "value": "4503c065-c965-4267-8dc8-cf42f410736f"
          }
        },
        "about": [
          null
        ],
        "recipient": [
          {
            "reference": "/RelatedPerson/eessssd-324534-34534-3455",
            "type": "RelatedPerson"
          }
        ]
      },
      "request": {
        "method": "POST"
      }
    }
  ]
}