#@host = https://test.ahdis.ch
@host =https://fhir.dk.swisstph-mis.ch

POST {{host}}/matchbox/fhir/Bundle HTTP/1.1
Content-Type: application/json
Accept-Encoding: gzip
Content-Encoding: gzip,deflate

< C:\Users\delcpa\Development\DAK-tools\bundle.json